---
title: "clase 25 09"
author: "Natalia Delgado Giraldo"
date: "2025-09-25"
output: html_document
---

```{r}
# install.packages("knitr")
# install.packages("gt")
# install.packages("kableExtra")
# install.packages("gaawr2",force= TRUE)
library(gaawr2)
library(dplyr)
library(kableExtra)
library(gt)
data(diabetes)
head(diabetes)
```

```{r}
kable(head(diabetes, 5), booktabs = TRUE) %>% kable_styling(font_size = 12)
```

```{r}
kable(head(diabetes, 5), booktabs = TRUE) %>% 
  kable_styling(font_size = 12) %>%
  kable_styling(bootstrap_options = "striped", full_width = F)
  
```

```{r}
kable(head(diabetes[1:2], 5), booktabs = TRUE) %>% 
  kable_styling(font_size = 12) %>%
  kable_styling(bootstrap_options = "striped", full_width = F)
```

```{r}
kable(head(diabetes[1:2, 4:5]), booktabs = TRUE) %>% 
  kable_styling(font_size = 12) %>%
  kable_styling(bootstrap_options = "striped", full_width = F)
```

```{r}
kable(head(diabetes[, 4:5]), booktabs = TRUE) %>% 
  kable_styling(font_size = 12) %>%
  kable_styling(bootstrap_options = "striped", full_width = F)
```

```{r}
kable(head(diabetes[, 4:5]), booktabs = TRUE) %>% 
  kable_styling(font_size = 12, position= "left",
  bootstrap_options = "striped", full_width = F)
```

```{r}
kable(head(diabetes, 5), booktabs = TRUE) %>% 
  kable_styling(font_size = 12) %>% 
  kable_styling(bootstrap_options = "striped",
                full_width = F) %>%
  add_header_above(c("Personal data" = 4, "Blood
                     Profile" =9, "weight" = 1))

```

```{r}
kable(diabetes, digits = 2, format = "html", row.names = TRUE) %>%
kable_styling(bootstrap_options = c("striped"),
full_width = T,
font_size = 15) %>%
scroll_box(height = "300px")

```


<br><br><br>


```{r}

```

