---
title: "Homework3"
author: "Natalia Delgado Giraldo"
date: "`r format(Sys.time(), '%Y-%b-%d, %I:%M %p')`"
output: html_document
---
install.packages("gapminder")

library(dplyr)
library(gapminder)

data(gapminder)
head(gapminder)

           country     continent  year lifeExp      pop gdpPercap
           <fct>       <fct>     <int>   <dbl>    <int>     <dbl>
         1 Afghanistan Asia       1952    28.8  8425333      779.
         2 Afghanistan Asia       1957    30.3  9240934      821.
         3 Afghanistan Asia       1962    32.0 10267083      853.
         4 Afghanistan Asia       1967    34.0 11537966      836.
         5 Afghanistan Asia       1972    36.1 13079460      740.
         6 Afghanistan Asia       1977    38.4 14880372      786.

**Q1**

class(gapminder)

"data.frame"

**Q2**

gapminder %>% 
  filter(lifeExp < 29)
  
      country     continent  year lifeExp     pop gdpPercap
      <fct>       <fct>     <int>   <dbl>   <int>     <dbl>
    1 Afghanistan Asia       1952    28.8 8425333      779.
    2 Rwanda      Africa     1992    23.6 7290203      737.

**Q3**

gapminder %>% 
  filter(country == "Rwanda", year > 1979)

       country continent  year lifeExp     pop gdpPercap
       <fct>   <fct>     <int>   <dbl>   <int>     <dbl>
     1 Rwanda  Africa     1982    46.2 5507565      882.
     2 Rwanda  Africa     1987    44.0 6349365      848.
     3 Rwanda  Africa     1992    23.6 7290203      737.
     4 Rwanda  Africa     1997    36.1 7212583      590.
     5 Rwanda  Africa     2002    43.4 7852401      786.
     6 Rwanda  Africa     2007    46.2 8860588      863.

**Q4**

gapminder %>%
select(-gdpPercap)


      country     continent  year lifeExp      pop
      <fct>       <fct>     <int>   <dbl>    <int>
    1 Afghanistan Asia       1952    28.8  8425333
    2 Afghanistan Asia       1957    30.3  9240934
    3 Afghanistan Asia       1962    32.0 10267083
    4 Afghanistan Asia       1967    34.0 11537966
    5 Afghanistan Asia       1972    36.1 13079460
    6 Afghanistan Asia       1977    38.4 14880372
    
**Q5**
gapminder %>%
arrange(desc (lifeExp))

     country          continent  year lifeExp       pop gdpPercap
     <fct>            <fct>     <int>   <dbl>     <int>     <dbl>
    1 Japan            Asia       2007    82.6 127467972    31656.
    2 Hong Kong, China Asia       2007    82.2   6980412    39725.
    3 Japan            Asia       2002    82   127065841    28605.
    4 Iceland          Europe     2007    81.8    301931    36181.
    5 Switzerland      Europe     2007    81.7   7554661    37506.
    6 Hong Kong, China Asia       2002    81.5   6762476    30209.    
    
**Q6**    
  



